/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.foomsproject.forms;

import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author Lucas
 */
public class CalculadoradeBotao extends javax.swing.JFrame {
    
    public String calculo = "";
     public List<Double> conta = new ArrayList<>();
     public List<String> operacao = new ArrayList<>();
     public String op = "";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoradeBotao.class.getName());

    public boolean terminouConta = false;
    /**
     * Creates new form CalculadoradeBotao
     */
    public CalculadoradeBotao() {
        initComponents();
        lbl67.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl67 = new javax.swing.JLabel();
        txt7 = new javax.swing.JButton();
        txt8 = new javax.swing.JButton();
        txtvisor = new javax.swing.JTextField();
        txt1 = new javax.swing.JButton();
        txt2 = new javax.swing.JButton();
        txt4 = new javax.swing.JButton();
        txt5 = new javax.swing.JButton();
        txt9 = new javax.swing.JButton();
        txt3 = new javax.swing.JButton();
        txt6 = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        mais = new javax.swing.JButton();
        vezes = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        txtvisor1 = new javax.swing.JTextField();
        btn0 = new javax.swing.JButton();
        btnponto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(92, 85, 107));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/foomsproject/forms/67nao.gif"))); // NOI18N
        getContentPane().add(lbl67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        txt7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt7.setText("7");
        txt7.addActionListener(this::txt7ActionPerformed);
        getContentPane().add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 76, 63));

        txt8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt8.setText("8");
        txt8.addActionListener(this::txt8ActionPerformed);
        getContentPane().add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 80, 63));

        txtvisor.setEditable(false);
        txtvisor.setBackground(new java.awt.Color(186, 188, 236));
        txtvisor.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        txtvisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtvisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 460, 90));

        txt1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt1.setText("1");
        txt1.addActionListener(this::txt1ActionPerformed);
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 76, 63));

        txt2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt2.setText("2");
        txt2.addActionListener(this::txt2ActionPerformed);
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 80, 63));

        txt4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt4.setText("4");
        txt4.addActionListener(this::txt4ActionPerformed);
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 76, 63));

        txt5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt5.setText("5");
        txt5.addActionListener(this::txt5ActionPerformed);
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, 63));

        txt9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt9.setText("9");
        txt9.addActionListener(this::txt9ActionPerformed);
        getContentPane().add(txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 80, 63));

        txt3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt3.setText("3");
        txt3.addActionListener(this::txt3ActionPerformed);
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 80, 63));

        txt6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt6.setText("6");
        txt6.addActionListener(this::txt6ActionPerformed);
        getContentPane().add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, 63));

        igual.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        igual.setText("=");
        igual.addActionListener(this::igualActionPerformed);
        getContentPane().add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 190, 63));

        mais.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        mais.setText("+");
        mais.addActionListener(this::maisActionPerformed);
        getContentPane().add(mais, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 90, 63));

        vezes.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        vezes.setText("x");
        vezes.addActionListener(this::vezesActionPerformed);
        getContentPane().add(vezes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 90, 63));

        menos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        menos.setText("-");
        menos.addActionListener(this::menosActionPerformed);
        getContentPane().add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 90, 63));

        dividir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dividir.setText("/");
        dividir.addActionListener(this::dividirActionPerformed);
        getContentPane().add(dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 90, 63));

        txtvisor1.setEditable(false);
        txtvisor1.setBackground(new java.awt.Color(213, 233, 253));
        txtvisor1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtvisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 460, 51));

        btn0.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(this::btn0ActionPerformed);
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, 60));

        btnponto.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 48)); // NOI18N
        btnponto.setText(".");
        btnponto.addActionListener(this::btnpontoActionPerformed);
        getContentPane().add(btnponto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 50, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt7ActionPerformed
        // TODO add your handling code here:
         //operacao operacao
     digitarnumero("7");
        
    }//GEN-LAST:event_txt7ActionPerformed

    private void txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8ActionPerformed

        // TODO add your handling code here:
         //operacao operacao
     digitarnumero("8");
       
    }//GEN-LAST:event_txt8ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed

/*public String calculo;
     public List<Double> conta = new ArrayList<>();
     public List<operacao> operacao = new ArrayList<>();
     */
     // TODO add your handling code here:
     //operacao operacao
     
     
     digitarnumero("1");
       
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
         //operacao operacao
    
     
     digitarnumero("2");
        
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
         //operacao operacao
     
     
     digitarnumero("4");
       
    }//GEN-LAST:event_txt4ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
         //operacao operacao
     
     
    digitarnumero("5");
       
    }//GEN-LAST:event_txt5ActionPerformed

    private void txt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt9ActionPerformed
        // TODO add your handling code here:
         //operacao operacao
     digitarnumero("9");
    }//GEN-LAST:event_txt9ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
         //operacao operacao
     
     
    digitarnumero("3");
      
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
        //operacao operacao
     digitarnumero("6");
    }//GEN-LAST:event_txt6ActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // TODO add your handling code here:
        conta.add(Double.parseDouble(calculo));
        Double cal = 0.0;
       for(int i = 0; i < operacao.size(); i ++){
           if(operacao.get(i).equals("X") || operacao.get(i).equals("/") ){
               if(operacao.get(i).equals("X")){
                   cal = conta.get(i) * conta.get(i + 1);
               }else if(operacao.get(i).equals("/")){
                   cal = conta.get(i) / conta.get(i + 1);
               }
               
               conta.set(i, cal);
               conta.remove(i + 1);
               operacao.remove(i);
               i--;
           }
       }
        for(int i = 0; i < operacao.size(); i ++){
           if(operacao.get(i).equals("+") || operacao.get(i).equals("-")){
               if(operacao.get(i).equals("+")){
                   cal = conta.get(i) + conta.get(i + 1);
               }else if(operacao.get(i).equals("-")){
                   cal = conta.get(i) - conta.get(i + 1);
               }
               
               conta.set(i, cal);
               conta.remove(i + 1);
               operacao.remove(i);
               i--;
           }
       }
        cal = conta.get(0);
        if (cal == 67.0) {
        lbl67.setVisible(true); // Se der 67, o meme aparece!
    }
        txtvisor.setText(String.valueOf(cal));
        conta.clear();
        operacao.clear();
        calculo = "";
        terminouConta = true;
        
    }//GEN-LAST:event_igualActionPerformed

    private void maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisActionPerformed
        // TODO add your handling code here:
       
         //operacao operacao
     conta.add(Double.parseDouble(calculo));
     
     
     calculo = "";
     operacao.add("+");
     txtvisor.setText(txtvisor.getText() + "+");
       
        
        
        
    }//GEN-LAST:event_maisActionPerformed

    private void vezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vezesActionPerformed
        // TODO add your handling code here:
       
         conta.add(Double.parseDouble(calculo));
     
     
     calculo = "";
     operacao.add("X");
     txtvisor.setText(txtvisor.getText() + "X");
     
       
    }//GEN-LAST:event_vezesActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
       
        conta.add(Double.parseDouble(calculo));
     
     
     calculo = "";
     operacao.add("-");
     txtvisor.setText(txtvisor.getText() + "-");
     
        
    }//GEN-LAST:event_menosActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        // TODO add your handling code here:
        
       
       
         conta.add(Double.parseDouble(calculo));
     
     
     calculo = "";
     operacao.add("/");
     txtvisor.setText(txtvisor.getText() + "/");
      
       
       
    }//GEN-LAST:event_dividirActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        
         digitarnumero("0");
      
        
        
        
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnpontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpontoActionPerformed
        // TODO add your handling code here:
        calculo += ".";
         txtvisor.setText(txtvisor.getText() + ".");
    }//GEN-LAST:event_btnpontoActionPerformed

    private void digitarnumero(String numero){
        if(terminouConta){
            txtvisor.setText("");
            calculo = "";
            terminouConta = false;
            lbl67.setVisible(false);
        }
        calculo += numero;
        txtvisor.setText(txtvisor.getText()+ numero);
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoradeBotao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btnponto;
    private javax.swing.JButton dividir;
    private javax.swing.JButton igual;
    private javax.swing.JLabel lbl67;
    private javax.swing.JButton mais;
    private javax.swing.JButton menos;
    private javax.swing.JButton txt1;
    private javax.swing.JButton txt2;
    private javax.swing.JButton txt3;
    private javax.swing.JButton txt4;
    private javax.swing.JButton txt5;
    private javax.swing.JButton txt6;
    private javax.swing.JButton txt7;
    private javax.swing.JButton txt8;
    private javax.swing.JButton txt9;
    private javax.swing.JTextField txtvisor;
    private javax.swing.JTextField txtvisor1;
    private javax.swing.JButton vezes;
    // End of variables declaration//GEN-END:variables
}
