/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.foomsproject.forms;

/**
 *
 * @author Lucas
 */
public class Form_principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_principal.class.getName());

    /**
     * Creates new form Form_principal
     */
    public Form_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mniCalculadoraPadrao = new javax.swing.JMenuItem();
        mniCalculadoraEq2Grau = new javax.swing.JMenuItem();
        mniCalculadoraEq2Grau1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        minsair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jMenu3.setText("Calculadoras");

        mniCalculadoraPadrao.setText("Calculadora Padrão");
        mniCalculadoraPadrao.addActionListener(this::mniCalculadoraPadraoActionPerformed);
        jMenu3.add(mniCalculadoraPadrao);

        mniCalculadoraEq2Grau.setText("Calculadora Equação 2°");
        mniCalculadoraEq2Grau.addActionListener(this::mniCalculadoraEq2GrauActionPerformed);
        jMenu3.add(mniCalculadoraEq2Grau);

        mniCalculadoraEq2Grau1.setText("Calculadora Padrao 2");
        mniCalculadoraEq2Grau1.addActionListener(this::mniCalculadoraEq2Grau1ActionPerformed);
        jMenu3.add(mniCalculadoraEq2Grau1);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Opções");

        minsair.setText("Sair");
        minsair.addActionListener(this::minsairActionPerformed);
        jMenu4.add(minsair);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCalculadoraPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCalculadoraPadraoActionPerformed
    new Calculadora().setVisible(true);
    }//GEN-LAST:event_mniCalculadoraPadraoActionPerformed

    private void mniCalculadoraEq2GrauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCalculadoraEq2GrauActionPerformed
        // TODO add your handling code here:
        new Form_CalculadorEqSegGrau().setVisible(true);
    }//GEN-LAST:event_mniCalculadoraEq2GrauActionPerformed

    private void minsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minsairActionPerformed
        // TODO add your handling code here
       System.exit(0);
    }//GEN-LAST:event_minsairActionPerformed

    private void mniCalculadoraEq2Grau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCalculadoraEq2Grau1ActionPerformed
        // TODO add your handling code here:
        //new Form_CalculadorEqSegGrau().setVisible(true);
        new CalculadoradeBotao().setVisible(true);
    }//GEN-LAST:event_mniCalculadoraEq2Grau1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem minsair;
    private javax.swing.JMenuItem mniCalculadoraEq2Grau;
    private javax.swing.JMenuItem mniCalculadoraEq2Grau1;
    private javax.swing.JMenuItem mniCalculadoraPadrao;
    // End of variables declaration//GEN-END:variables
}
